name: Docker build

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-image.yml
      - Dockerfile
      - entrypoint.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build-and-push-docker-image:
    if: github.repository_owner == 'nowsprinting' # Skip on forked repo
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      packages: write
    env:
      DIFF_PDF_VERSION: 'v0.5.2'

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        with:
          context: .
          build-args: REPO_REF=${{ env.DIFF_PDF_VERSION }}
          push: true
          labels: org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/diff-pdf:latest
            ghcr.io/${{ github.repository_owner }}/diff-pdf:${{ env.DIFF_PDF_VERSION }}

      - uses: 8398a7/action-slack@1750b5085f3ec60384090fb7c52965ef822e869e # v3
        with:
          status: ${{ job.status }}
          fields: repo,message,job,pullRequest
          mention: here
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: failure() && github.repository_owner == 'nowsprinting' # Skip public fork, because can not read secrets.
