name: Lint Dockerfile

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/hadolint.yml
      - Dockerfile
  pull_request:
    types: [ opened, synchronize, reopened ]  # Same as default
    paths:
      - .github/workflows/hadolint.yml
      - Dockerfile

permissions: write-all
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: Dockerfile

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,job,pullRequest
          mention: here
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: failure() && github.repository_owner == 'nowsprinting' # Skip public fork, because can not read secrets.
