name: Lint Dockerfile

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/hadolint.yml
      - Dockerfile
  pull_request:
    types: [ opened, synchronize, reopened ]  # Same as default
    paths:
      - .github/workflows/hadolint.yml
      - Dockerfile

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Lint
        uses: hadolint/hadolint-action@d292784f8f3eacda47060b259a580467b0ba410c # master
        with:
          dockerfile: Dockerfile

      - uses: 8398a7/action-slack@1750b5085f3ec60384090fb7c52965ef822e869e # v3
        with:
          status: ${{ job.status }}
          fields: repo,message,job,pullRequest
          mention: here
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: failure() && github.event.pull_request.head.repo.fork == false # Skip on public fork, because can not read secrets.
