name: Update major and latest refs  # for GitHub Actions, see https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#versioning

on:
  push:
    tags:
      - 'v*'
  release:
    types: [ published ]

jobs:
  update-major:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: v

      - uses: actions/checkout@v3
        if: steps.version.outputs.is_valid == 'true'

      - name: Update major and latest branches
        run: |
          git push --force origin 'HEAD:refs/heads/${{ steps.version.outputs.major_prerelease }}'
          git push --force origin 'HEAD:refs/heads/latest'
        if: steps.version.outputs.is_valid == 'true'
